package name.mi.buyer.mdalpha.map;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class EncodeMap {
    private static final Map<String, String> mMap;

    private static final String DEFAULT = "";

    static {
        Map<String, String> vMap = new HashMap<>();
        vMap.put("major_condition_emphysema", "zU");
        vMap.put("bachelor", "vj");
        vMap.put("both", "vl");
        vMap.put("Freeway Insurance", "wd");
        vMap.put("form", "b");
        vMap.put("email", "Z");
        vMap.put("Liberty Mutual", "xD");
        vMap.put("No insurance", "xS");
        vMap.put("Act of Nature", "vS");
        vMap.put("life", "j");
        vMap.put("major_condition_high_blood_pressure", "zZ");
        vMap.put("annual_mileage", "F");
        vMap.put("collision", "L");
        vMap.put("HONDA", "yn");
        vMap.put("military", "zj");
        vMap.put("other non technical", "xa");
        vMap.put("Flood damage", "wZ");
        vMap.put("home_garage", "h");
        vMap.put("claim", "vu");
        vMap.put("married", "m");
        vMap.put("Rearended by another person", "xw");
        vMap.put("marketing", "xF");
        vMap.put("Hit by another person", "wr");
        vMap.put("TOYOTA", "ym");
        vMap.put("Auto-Owners", "vh");
        vMap.put("certified public accountant", "vr");
        vMap.put("spouse", "yE");
        vMap.put("American Automobile Insurance", "vZ");
        vMap.put("major_condition_heart_disease", "zX");
        vMap.put("bankruptcy", "I");
        vMap.put("Inattentive driving", "w2");
        vMap.put("Sante Fe", "x6");
        vMap.put("home_length", "f");
        vMap.put("More than 20 MPH over", "xO");
        vMap.put("ad_unit", "D");
        vMap.put("JAGUAR", "zD");
        vMap.put("version", "vK");
        vMap.put("health", "d");
        vMap.put("The Hartford", "yO");
        vMap.put("address2", "C");
        vMap.put("high school", "wo");
        vMap.put("average", "vi");
        vMap.put("minor not applicable", "xM");
        vMap.put("driver", "W");
        vMap.put("GEO", "zH");
        vMap.put("not applicable", "xU");
        vMap.put("model", "n");
        vMap.put("school teacher", "x7");
        vMap.put("incomplete", "w5");
        vMap.put("retail", "xz");
        vMap.put("Ameriprise", "vb");
        vMap.put("suspended_reason", "vH");
        vMap.put("address", "A");
        vMap.put("Ran a stop sign", "xv");
        vMap.put("primary_vehicle", "t");
        vMap.put("AIG", "vU");
        vMap.put("Allied", "vW");
        vMap.put("Amica", "vc");
        vMap.put("data", "V");
        vMap.put("Peachtree", "xh");
        vMap.put("accident_at_fault", "vR");
        vMap.put("Illegal lane change", "ww");
        vMap.put("zip", "vM");
        vMap.put("current_policy_expires", "U");
        vMap.put("administrative clerical", "vT");
        vMap.put("type", "vI");
        vMap.put("Grange", "wi");
        vMap.put("motorcycle", "o");
        vMap.put("clergy", "vv");
        vMap.put("pleasure", "xn");
        vMap.put("physician", "xm");
        vMap.put("DODGE", "yl");
        vMap.put("major_condition_vascular_disease", "zi");
        vMap.put("primary_purpose", "s");
        vMap.put("Other Unlisted Moving Violation", "xd");
        vMap.put("Mendota", "xH");
        vMap.put("MITSUBISHI", "yu");
        vMap.put("Fred Loya", "wc");
        vMap.put("birth_date", "J");
        vMap.put("phone", "q");
        vMap.put("auto", "G");
        vMap.put("Permanent General", "xk");
        vMap.put("Hit an animal", "wp");
        vMap.put("Safeway Insurance", "x3");
        vMap.put("coverage_amount", "zJ");
        vMap.put("KIA", "yz");
        vMap.put("major_condition_diabetes", "zT");
        vMap.put("CADILLAC", "y5");
        vMap.put("Imperial Fire & Casualty", "w1");
        vMap.put("Elephant", "wF");
        vMap.put("First Acceptance", "wY");
        vMap.put("American Family", "va");
        vMap.put("unemployed", "yV");
        vMap.put("Insurance Depot", "w7");
        vMap.put("accident", "vQ");
        vMap.put("Countrywide", "v1");
        vMap.put("high_risk", "zM");
        vMap.put("description", "v7");
        vMap.put("LINCOLN", "zB");
        vMap.put("Nationwide", "xQ");
        vMap.put("people", "xj");
        vMap.put("PLYMOUTH", "zC");
        vMap.put("engineer", "wG");
        vMap.put("Allstate", "vX");
        vMap.put("Standard Protection", "yF");
        vMap.put("Drug possession", "wC");
        vMap.put("SATURN", "y3");
        vMap.put("car_leased", "K");
        vMap.put("sales inside", "x4");
        vMap.put("scientist", "x8");
        vMap.put("good", "wh");
        vMap.put("local_hour", "k");
        vMap.put("major_condition_stroke", "zg");
        vMap.put("Anchor General", "ve");
        vMap.put("master", "xG");
        vMap.put("education", "Y");
        vMap.put("work", "yh");
        vMap.put("child", "vs");
        vMap.put("Collided with another car", "vw");
        vMap.put("first_licensed", "a");
        vMap.put("MERCURY", "y1");
        vMap.put("associate", "vg");
        vMap.put("retired", "x0");
        vMap.put("LAND ROVER", "zI");
        vMap.put("Peak Property and Casualty Insurance", "xi");
        vMap.put("coverage", "zK");
        vMap.put("Open container", "xX");
        vMap.put("prescription_medications", "zk");
        vMap.put("self", "x9");
        vMap.put("what_damaged", "ye");
        vMap.put("Driving too fast for conditions", "wA");
        vMap.put("address_2", "B");
        vMap.put("ACURA", "y4");
        vMap.put("sub_1", "vD");
        vMap.put("Wrong way on a one way", "yi");
        vMap.put("LEXUS", "y9");
        vMap.put("skilled semi skilled", "yC");
        vMap.put("No coverage", "xR");
        vMap.put("professor", "xq");
        vMap.put("major_condition_cancer", "zR");
        vMap.put("Commerce West", "vx");
        vMap.put("construction trades", "vy");
        vMap.put("Windshield Replacement", "yg");
        vMap.put("major_condition_hepatitis_liver", "zY");
        vMap.put("sub_3", "vF");
        vMap.put("major_condition_mental_illness", "zc");
        vMap.put("major_condition_multiple_sclerosis", "zd");
        vMap.put("incident_date", "w3");
        vMap.put("other", "xY");
        vMap.put("Minor in possession", "xL");
        vMap.put("comprehensive", "M");
        vMap.put("tobacco", "zl");
        vMap.put("major_condition_alcohol_drug_abuse", "zO");
        vMap.put("professional salaried", "xp");
        vMap.put("Dairyland Insurance", "v3");
        vMap.put("Reckless endangerment", "xy");
        vMap.put("ISUZU", "zF");
        vMap.put("Illegal passing", "wx");
        vMap.put("major_condition_heart_attack", "zW");
        vMap.put("amount_paid", "vd");
        vMap.put("home_ownership", "g");
        vMap.put("contact", "N");
        vMap.put("Failure to obey traffic signal", "wR");
        vMap.put("Omni Insurance", "xW");
        vMap.put("ticket", "yP");
        vMap.put("Shelter", "yB");
        vMap.put("continuous_coverage", "O");
        vMap.put("current_customer", "S");
        vMap.put("GMC", "yp");
        vMap.put("Theft of stereo", "yL");
        vMap.put("incidents", "w4");
        vMap.put("submodel", "vG");
        vMap.put("Cure", "v2");
        vMap.put("USAA", "yY");
        vMap.put("Theft of vehicle", "yM");
        vMap.put("DUI/DWAI", "wE");
        vMap.put("major_condition_ulcers", "zh");
        vMap.put("major_condition_pulmonary_disease", "zf");
        vMap.put("INFINITI", "zE");
        vMap.put("Expired Registration", "wP");
        vMap.put("Safeco", "x2");
        vMap.put("major_condition_kidney_disease", "zb");
        vMap.put("Failure to yield", "wU");
        vMap.put("High Point Insurance", "wn");
        vMap.put("dui", "wD");
        vMap.put("Travelers", "yT");
        vMap.put("Explorer", "wQ");
        vMap.put("financial services", "wX");
        vMap.put("BUICK", "y0");
        vMap.put("credit_rating", "Q");
        vMap.put("renter", "vB");
        vMap.put("below average", "vk");
        vMap.put("Bristol West", "vm");
        vMap.put("Equity Auto Insurance", "wH");
        vMap.put("SUBARU", "y6");
        vMap.put("Driving without a license", "wB");
        vMap.put("poor", "xo");
        vMap.put("major_condition_epilepsy", "zV");
        vMap.put("health care", "wm");
        vMap.put("Illegal U Turn", "w0");
        vMap.put("MetLife", "xJ");
        vMap.put("Following too close", "wa");
        vMap.put("Towing service", "yR");
        vMap.put("GEICO", "wf");
        vMap.put("National Insurance", "xP");
        vMap.put("SAAB", "zG");
        vMap.put("AUDI", "y7");
        vMap.put("human relations", "wu");
        vMap.put("Viking Insurance", "yc");
        vMap.put("Hail damage", "wj");
        vMap.put("Progressive", "xr");
        vMap.put("sales outside", "x5");
        vMap.put("height", "zL");
        vMap.put("Country Insurance and Financial Services", "v0");
        vMap.put("license_active", "i");
        vMap.put("major_condition_alzheimers_dementia", "zP");
        vMap.put("other technical", "xc");
        vMap.put("AAA", "vO");
        vMap.put("United Insurance", "yW");
        vMap.put("FORD", "yk");
        vMap.put("Defective Equipment", "v4");
        vMap.put("major_condition_asthma", "zQ");
        vMap.put("More than 10 MPH over", "xN");
        vMap.put("self employed", "yA");
        vMap.put("weight", "zm");
        vMap.put("placement_id", "r");
        vMap.put("consultant", "vz");
        vMap.put("IFA Auto Insurance", "wv");
        vMap.put("liability_medical_paid", "xC");
        vMap.put("some college", "yD");
        vMap.put("Foremost", "wb");
        vMap.put("Windhaven", "yf");
        vMap.put("Farm Bureau/Farm Family/Rural", "wV");
        vMap.put("Carpool lane violation", "vq");
        vMap.put("Passing in a no-passing zone", "xf");
        vMap.put("Car fire", "vp");
        vMap.put("Careless driving", "vo");
        vMap.put("other not listed", "xb");
        vMap.put("drivers", "X");
        vMap.put("Hanover", "wl");
        vMap.put("American Alliance Insurance", "vY");
        vMap.put("manager supervisor", "xE");
        vMap.put("Other", "xZ");
        vMap.put("currently_insured", "T");
        vMap.put("NISSAN", "yo");
        vMap.put("dentist", "v6");
        vMap.put("Passing a school bus", "xe");
        vMap.put("make", "l");
        vMap.put("current_company", "R");
        vMap.put("Child not in car seat", "vt");
        vMap.put("Mercury", "xI");
        vMap.put("BMW", "yv");
        vMap.put("Failure to signal", "wS");
        vMap.put("Erie Insurance", "wI");
        vMap.put("MERCEDES-BENZ", "yx");
        vMap.put("CHEVROLET", "yj");
        vMap.put("major_condition_aids_hiv", "zN");
        vMap.put("SafeAuto", "x1");
        vMap.put("major_condition_clinical_depression", "zS");
        vMap.put("Failure to stop", "wT");
        vMap.put("Illegal turn", "wy");
        vMap.put("PONTIAC", "yq");
        vMap.put("Excessive noise", "wL");
        vMap.put("sub_2", "vE");
        vMap.put("ua_class", "u");
        vMap.put("Hallmark", "wk");
        vMap.put("property", "xt");
        vMap.put("suspension", "yK");
        vMap.put("Wawanesa Mutual", "yd");
        vMap.put("phd", "xl");
        vMap.put("Access Insurance", "vP");
        vMap.put("Expired emissions", "wO");
        vMap.put("Victoria", "yb");
        vMap.put("Ocean Harbor", "xV");
        vMap.put("Pronto", "xs");
        vMap.put("Passing on shoulder", "xg");
        vMap.put("Titan", "yQ");
        vMap.put("sr_22", "vC");
        vMap.put("Exhibition driving", "wM");
        vMap.put("relationship", "vA");
        vMap.put("Alfa", "vV");
        vMap.put("Less than 10 MPH over", "xB");
        vMap.put("student", "yI");
        vMap.put("Defective vehicle (reduced violation)", "v5");
        vMap.put("alarm", "E");
        vMap.put("home", "e");
        vMap.put("gender", "c");
        vMap.put("architect", "vf");
        vMap.put("State Minimum", "yH");
        vMap.put("Ran a red light", "xu");
        vMap.put("VOLVO", "zA");
        vMap.put("JEEP", "yy");
        vMap.put("Gainsco", "we");
        vMap.put("exclude_carriers", "zn");
        vMap.put("HYUNDAI", "yt");
        vMap.put("Illegal turn on red", "wz");
        vMap.put("year", "vL");
        vMap.put("UAIC", "yU");
        vMap.put("US Agencies", "yZ");
        vMap.put("InsureOne", "w8");
        vMap.put("Reckless driving", "xx");
        vMap.put("major_condition_high_cholesterol", "za");
        vMap.put("lawyer", "xA");
        vMap.put("Vandalism", "ya");
        vMap.put("Superior Protection", "yJ");
        vMap.put("coverage_type", "P");
        vMap.put("MAZDA", "yw");
        vMap.put("VOLKSWAGEN", "ys");
        vMap.put("Unitrin Direct", "yX");
        vMap.put("occupation", "p");
        vMap.put("business owner", "vn");
        vMap.put("The General", "yN");
        vMap.put("Infinity Insurance", "w6");
        vMap.put("CHRYSLER", "yr");
        vMap.put("State Farm", "yG");
        vMap.put("Direct General", "v8");
        vMap.put("No seatbelt", "xT");
        vMap.put("transportation or logistics", "yS");
        vMap.put("disabled", "v9");
        vMap.put("Kemper", "w9");
        vMap.put("vehicles", "vJ");
        vMap.put("Farmers", "wW");
        vMap.put("Hit while stopped", "ws");
        vMap.put("OLDSMOBILE", "y2");
        vMap.put("SUZUKI", "y8");
        vMap.put("GMAC", "wg");
        vMap.put("Expired drivers license", "wN");
        vMap.put("Hit an obstruction. Single car accident", "wq");
        vMap.put("military enlisted", "xK");
        vMap.put("excellent", "wK");
        vMap.put("average_mileage", "H");
        vMap.put("homemaker", "wt");
        vMap.put("21st Century", "vN");
        vMap.put("major_condition_other", "ze");
        vMap.put("Esurance", "wJ");

        mMap = Collections.unmodifiableMap(vMap);
    }

    public static String valueOf(String iKey) {
        if (iKey == null)
            return DEFAULT;
        String vValue = mMap.get(iKey);
        if (vValue == null)
            vValue = iKey;
        return vValue;
    }
}
