package name.mi.auto.enumerate;

public enum AdCompany {
    _21ST_CENTURY_INSURANCE("21st Century Insurance"),
    _AAA_AUTO_CLUB("AAA / Auto Club"),
    _AARP_AUTO_INSURANCE("AARP Auto Insurance"),
    _AIU_INSURANCE("AIU Insurance"),
    _ALLIED("Allied"),
    _ALLSTATE("Allstate"),
    _AMERICAN_ALLIANCE_INSURANCE("American Alliance Insurance"),
    _AMERICAN_AUTOMOBILE_INSURANCE("American Automobile Insurance"),
    _AMERICAN_CASUALTY("American Casualty"),
    _AMERICAN_DEPOSIT_INSURANCE("American Deposit Insurance"),
    _AMERICAN_DIRECT_BUSINESS_INSURANCE("American Direct Business Insurance"),
    _AMERICAN_EMPIRE_INSURANCE("American Empire Insurance"),
    _AMERICAN_FAMILY("American Family"),
    _AMERICAN_FINANCIAL("American Financial"),
    _AMERICAN_HOME_ASSURANCE("American Home Assurance"),
    _AMERICAN_INSURANCE("American Insurance"),
    _AMERICAN_INTERNATIONAL_INS("American International Ins"),
    _AMERICAN_INTERNATIONAL_PACIFIC("American International Pacific"),
    _AMERICAN_INTERNATIONAL_SOUTH("American International South"),
    _AMERICAN_MANUFACTURERS("American Manufacturers"),
    _AMERICAN_MAYFLOWER_INSURANCE("American Mayflower Insurance"),
    _AMERICAN_MOTORISTS_INSURANCE("American Motorists Insurance"),
    _AMERICAN_NATIONAL_INSURANCE("American National Insurance"),
    _AMERICAN_PREMIER_INSURANCE("American Premier Insurance"),
    _AMERICAN_PROTECTION_INSURANCE("American Protection Insurance"),
    _AMERICAN_SERVICE_INSURANCE("American Service Insurance"),
    _AMERICAN_SKYLINE_INSURANCE_COMPANY("American Skyline Insurance Company"),
    _AMERICAN_SPIRIT_INSURANCE("American Spirit Insurance"),
    _AMERICAN_STANDARD_INSURANCE_OH("American Standard Insurance - OH"),
    _AMERICAN_STANDARD_INSURANCE_WI("American Standard Insurance - WI"),
    _AMICA("Amica"),
    _ARBELLA("Arbella"),
    _ASSOCIATED_INDEMNITY("Associated Indemnity"),
    _ATLANTA_CASUALTY("Atlanta Casualty"),
    _ATLANTIC_INDEMNITY("Atlantic Indemnity"),
    _AUTO_CLUB_INSURANCE_COMPANY("Auto Club Insurance Company"),
    _AUTO_OWNERS("Auto Owners"),
    _BLUE_CROSS_AND_BLUE_SHIELD("Blue Cross and Blue Shield"),
    _CAL_FARM_INSURANCE("Cal Farm Insurance"),
    _CALIFORNIA_STATE_AUTOMOBILE_ASSOCIATION("California State Automobile Association"),
    _CHUBB("Chubb"),
    _CITIZENS("Citizens"),
    _CLARENDON_AMERICAN_INSURANCE("Clarendon American Insurance"),
    _CLARENDON_NATIONAL_INSURANCE("Clarendon National Insurance"),
    _CNA("CNA"),
    _COLONIAL_INSURANCE("Colonial Insurance"),
    _CONTINENTAL_CASUALTY("Continental Casualty"),
    _CONTINENTAL_DIVIDE_INSURANCE("Continental Divide Insurance"),
    _CONTINENTAL_INSURANCE("Continental Insurance"),
    _COTTON_STATES_INSURANCE("Cotton States Insurance"),
    _COUNTRY_INSURANCE_FINANCIAL_SERVICES("Country Insurance & Financial Services"),
    _DAIRYLAND_COUNTY_MUTUAL_CO_OF_TX("Dairyland County Mutual Co of TX"),
    _DAIRYLAND_INSURANCE("Dairyland Insurance"),
    _DASHERS_INSURANCE_SERVICES("Dashers Insurance Services"),
    _DIRECT_GENERAL_AUTO_INSURANCE("Direct General Auto Insurance"),
    _EASTWOOD_INSURANCE("Eastwood Insurance"),
    _ELECTRIC_INSURANCE("Electric Insurance"),
    _ERIE("Erie"),
    _ESURANCE("Esurance"),
    _FARM_BUREAU("Farm Bureau"),
    _FARMERS("Farmers"),
    _FIRE_AND_CASUALTY_INSURANCE_CO_OF_CT("Fire and Casualty Insurance Co of CT"),
    _FIREMANS_FUND("Firemans Fund"),
    _GEICO("GEICO"),
    _GMAC_INSURANCE("GMAC Insurance"),
    _GOLDEN_RULE_INSURANCE("Golden Rule Insurance"),
    _GOVERNMENT_EMPLOYEES_INSURANCE("Government Employees Insurance"),
    _GRANGE("Grange"),
    _GUARANTY_NATIONAL_INSURANCE("Guaranty National Insurance"),
    _HANOVER_LLOYDS_INSURANCE_COMPANY("Hanover Lloyds Insurance Company"),
    _HEALTH_PLUS_OF_AMERICA("Health Plus of America"),
    _IFA_AUTO_INSURANCE("IFA Auto Insurance"),
    _IGF_INSURANCE("IGF Insurance"),
    _INFINITY_INSURANCE("Infinity Insurance"),
    _INFINITY_NATIONAL_INSURANCE("Infinity National Insurance"),
    _INFINITY_SELECT_INSURANCE("Infinity Select Insurance"),
    _INTEGON("Integon"),
    _KAISER_PERMANENTE("Kaiser Permanente"),
    _KEMPER_LLOYDS_INSURANCE("Kemper Lloyds Insurance"),
    _LANDMARK_AMERICAN_INSURANCE("Landmark American Insurance"),
    _LEADER_NATIONAL_INSURANCE("Leader National Insurance"),
    _LEADER_PREFERRED_INSURANCE("Leader Preferred Insurance"),
    _LEADER_SPECIALTY_INSURANCE("Leader Specialty Insurance"),
    _LIBERTY_INSURANCE_CORP("Liberty Insurance Corp"),
    _LIBERTY_MUTUAL("Liberty Mutual"),
    _LIBERTY_NORTHWEST_INSURANCE("Liberty Northwest Insurance"),
    _LUMBERMENS_MUTUAL("Lumbermens Mutual"),
    _MASS_MUTUAL("Mass Mutual"),
    _MERCURY("Mercury"),
    _METLIFE("MetLife"),
    _METROPOLITAN_INSURANCE_CO("Metropolitan Insurance Co."),
    _MID_CENTURY_INSURANCE("Mid Century Insurance"),
    _MID_CONTINENT_CASUALTY("Mid-Continent Casualty"),
    _MIDDLESEX_INSURANCE("Middlesex Insurance"),
    _MIDWEST_NATIONAL_LIFE("Midwest National Life"),
    _MSI_INSURANCE("MSI Insurance"),
    _MUTUAL_OF_NEW_YORK("Mutual of New York"),
    _MUTUAL_OF_OMAHA("Mutual of Omaha"),
    _NATIONAL_BEN_FRANKLIN_INSURANCE("National Ben Franklin Insurance"),
    _NATIONAL_CASUALTY("National Casualty"),
    _NATIONAL_CONTINENTAL_INSURANCE("National Continental Insurance"),
    _NATIONAL_FIRE_INSURANCE_COMPANY_OF_HARTFORD("National Fire Insurance Company of Hartford"),
    _NATIONAL_HEALTH_INSURANCE("National Health Insurance"),
    _NATIONAL_INDEMNITY("National Indemnity"),
    _NATIONAL_UNION_FIRE_INSURANCE_OF_LA("National Union Fire Insurance of LA"),
    _NATIONAL_UNION_FIRE_INSURANCE_OF_PA("National Union Fire Insurance of PA"),
    _NATIONWIDE("Nationwide"),
    _NEW_YORK_LIFE("New York Life"),
    _NORTHWESTERN_MUTUAL_LIFE("Northwestern Mutual Life"),
    _NORTHWESTERN_PACIFIC_INDEMNITY("Northwestern Pacific Indemnity"),
    _OMNI_INDEMNITY("Omni Indemnity"),
    _OMNI_INSURANCE("Omni Insurance"),
    _ORION_INSURANCE("Orion Insurance"),
    _PACIFIC_INDEMNITY("Pacific Indemnity"),
    _PACIFIC_INSURANCE("Pacific Insurance"),
    _PAFCO_GENERAL_INSURANCE("Pafco General Insurance"),
    _PATRIOT_GENERAL_INSURANCE("Patriot General Insurance"),
    _PEAK_PROPERTY_AND_CASUALTY_INSURANCE("Peak Property and Casualty Insurance"),
    _PEMCO_INSURANCE("PEMCO Insurance"),
    _PROGRESSIVE("Progressive"),
    _PROGRESSIVE_AUTO_PRO("Progressive Auto Pro"),
    _PRUDENTIAL("Prudential"),
    _RELIANCE_INSURANCE("Reliance Insurance"),
    _RELIANCE_NATIONAL_INDEMNITY("Reliance National Indemnity"),
    _RELIANCE_NATIONAL_INSURANCE("Reliance National Insurance"),
    _REPUBLIC_INDEMNITY("Republic Indemnity"),
    _RESPONSE_INSURANCE("Response Insurance"),
    _SAFECO("Safeco"),
    _SAFEWAY_INSURANCE("Safeway Insurance"),
    _SAFEWAY_INSURANCE_CO_OF_AL("Safeway Insurance Co of AL"),
    _SAFEWAY_INSURANCE_CO_OF_GA("Safeway Insurance Co of GA"),
    _SAFEWAY_INSURANCE_CO_OF_LA("Safeway Insurance Co of LA"),
    _SECURITY_INSURANCE_CO_OF_HARTFORD("Security Insurance Co of Hartford"),
    _SECURITY_NATIONAL_INSURANCE_CO_OF_FL("Security National Insurance Co of FL"),
    _SENTINEL_INSURANCE("Sentinel Insurance"),
    _SENTRY_INSURANCE_A_MUTUAL_COMPANY("Sentry Insurance a Mutual Company"),
    _SENTRY_INSURANCE_GROUP("Sentry Insurance Group"),
    _SHELTER_INSURANCE_CO("Shelter Insurance Co."),
    _ST_PAUL("St. Paul"),
    _ST_PAUL_FIRE_AND_MARINE("St. Paul Fire and Marine"),
    _ST_PAUL_INSURANCE("St. Paul Insurance"),
    _STANDARD_FIRE_INSURANCE_COMPANY("Standard Fire Insurance Company"),
    _STATE_AND_COUNTY_MUTUAL_FIRE_INSURANCE("State and County Mutual Fire Insurance"),
    _STATE_FARM("State Farm"),
    _STATE_FARM_MUTUAL_AUTO("State Farm Mutual Auto"),
    _STATE_NATIONAL_INSURANCE("State National Insurance"),
    _SUPERIOR_AMERICAN_INSURANCE("Superior American Insurance"),
    _SUPERIOR_GUARANTY_INSURANCE("Superior Guaranty Insurance"),
    _SUPERIOR_INSURANCE("Superior Insurance"),
    _THE_AHBE_GROUP("The Ahbe Group"),
    _THE_GENERAL("The General"),
    _THE_HARTFORD("The Hartford"),
    _TICO_INSURANCE("TICO Insurance"),
    _TIG_COUNTRYWIDE_INSURANCE("TIG Countrywide Insurance"),
    _TRAVELERS("Travelers"),
    _TRAVELERS_INDEMNITY("Travelers Indemnity"),
    _TRI_STATE_CONSUMER_INSURANCE("Tri-State Consumer Insurance"),
    _TWIN_CITY_FIRE_INSURANCE("Twin City Fire Insurance"),
    _UNICARE("UniCare"),
    _UNITED_PACIFIC_INSURANCE("United Pacific Insurance"),
    _UNITED_SECURITY("United Security"),
    _UNITED_SERVICES_AUTOMOBILE_ASSOCIATION("United Services Automobile Association"),
    _UNITRIN_DIRECT("Unitrin Direct"),
    _USAA("USAA"),
    _USF_AND_G("USF and G"),
    _VIKING_COUNTY_MUTUAL_INSURANCE("Viking County Mutual Insurance"),
    _VIKING_INSURANCE_CO_OF_WI("Viking Insurance Co of WI"),
    _WINDSOR_INSURANCE("Windsor Insurance"),
    _WOODLANDS_FINANCIAL_GROUP("Woodlands Financial Group"),
    _COMPANY_NOT_LISTED("");

    private String mValueName;

    private AdCompany(String iValueName)
    {
        mValueName = iValueName;
    }

    public String getValueName()
    {
        return mValueName;
    }

    public static AdCompany parseAdCompany(String iValue)
    {
        for (AdCompany vValue : values())
        {
            if (vValue.getValueName().equals(iValue))
                return vValue;
        }
        return null;
    }

    public static AdCompany getValueOf(String iValue)
    {
        if (iValue == null)
            return null;
        return valueOf(iValue);
    }
}
