DROP TABLE IF EXISTS `Health_Form`;
CREATE TABLE `Health_Form` (
`id`  int(11) NOT NULL AUTO_INCREMENT ,
`created_ts`  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`updated_ts`  timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ,
`arrival_id`  int(11) NOT NULL DEFAULT 0 ,
`user_id`  int(11) NOT NULL DEFAULT 0 ,
`gender`  enum('Female','Male') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
`birthdate`  date NOT NULL ,
`height_ft`  int(11) NOT NULL DEFAULT 0 ,
`height_in`  int(11) NOT NULL DEFAULT 0 ,
`height_cm`  float NOT NULL DEFAULT 0 ,
`weight_lbs`  float NOT NULL DEFAULT 0 ,
`weight_kg`  float NOT NULL DEFAULT 0 ,
`tobacco`  tinyint(1) NOT NULL DEFAULT 0 ,
`marital`  enum('Single','Married','Divorced','Widowed') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
`spouse_inc`  tinyint(1) NOT NULL DEFAULT 0 ,
`spouse_first_name`  varchar(2047) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' ,
`spouse_last_name`  varchar(2047) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' ,
`spouse_gender`  enum('Female','Male') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
`spouse_birthdate`  date NOT NULL ,
`spouse_height_ft`  int(11) NOT NULL DEFAULT 0 ,
`spouse_height_in`  int(11) NOT NULL DEFAULT 0 ,
`spouse_height_cm`  float NOT NULL DEFAULT 0 ,
`spouse_weight_lbs`  float NOT NULL DEFAULT 0 ,
`spouse_weight_kg`  float NOT NULL DEFAULT 0 ,
`spouse_tobacco`  tinyint(1) NOT NULL DEFAULT 0 ,
`children`  int(11) NOT NULL DEFAULT 0 ,
`pregnant`  tinyint(1) NOT NULL DEFAULT 0 ,
`major_treatment`  tinyint(1) NOT NULL DEFAULT 0 ,
`hospitalized`  tinyint(1) NOT NULL DEFAULT 0 ,
`deny`  tinyint(1) NOT NULL DEFAULT 0 ,
`self_employ`  tinyint(1) NOT NULL DEFAULT 0 ,
`current_coverage`  tinyint(1) NOT NULL DEFAULT 0 ,
`prescription`  tinyint(1) NOT NULL DEFAULT 0 ,
`health_condition`  tinyint(1) NOT NULL DEFAULT 0 ,
`current_provider`  varchar(1023) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' ,
`prescription_list`  varchar(2047) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' ,
`health_condition_list`  varchar(2047) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' ,
`first_name`  varchar(1023) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' ,
`last_name`  varchar(1023) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' ,
`street`  varchar(1023) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' ,
`city`  varchar(511) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' ,
`state`  varchar(127) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' ,
`zipcode`  varchar(63) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' ,
`day_phone`  varchar(127) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' ,
`evening_phone`  varchar(127) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' ,
`email`  varchar(511) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' ,
PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
AUTO_INCREMENT=8
ROW_FORMAT=COMPACT
;

