-- ----------------------------
-- Records of Arrival_Tracking_Parameters
-- ----------------------------
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('29', 'tap011', 'network', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('30', 'tap014', 'network', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('31', 'tap017', 'network', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('32', 'tap019', 'network', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('33', 'tap021', 'device', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('34', 'tap024', 'device', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('35', 'tap028', 'device', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('36', 'tap029', 'device', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('37', 'tap032', 'devicemodel', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('38', 'tap033', 'devicemodel', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('39', 'tap037', 'devicemodel', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('40', 'tap038', 'devicemodel', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('41', 'tap041', 'ifmobile', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('42', 'tap043', 'ifmobile', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('43', 'tap044', 'ifmobile', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('44', 'tap045', 'ifmobile', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('45', 'tap051', 'placement', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('46', 'tap053', 'placement', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('47', 'tap057', 'placement', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('48', 'tap058', 'placement', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('49', 'tap064', 'target', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('50', 'tap065', 'target', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('51', 'tap066', 'target', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('52', 'tap069', 'target', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('53', 'tap071', 'aceid', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('54', 'tap074', 'aceid', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('55', 'tap077', 'aceid', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('56', 'tap078', 'aceid', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('57', 'tap092', 'sid', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('58', 'tap098', 'sid', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('59', 'tap095', 'sid', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('60', 'tap094', 'sid', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('61', 'tap114', 'subid', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('62', 'tap117', 'subid', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('63', 'tap113', 'subid', null);
INSERT INTO `Arrival_Tracking_Parameters` VALUES ('64', 'tap118', 'subid', null);