package name.mi.buyer.webjuice.map;

import name.mi.auto.enumerate.Company;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class CompanyMap
{
    private static final Map<Company, String> mMap;
    private static final String DEFAULT = "Company Not Listed";

    static
    {
        Map<Company, String> vMap = new HashMap<Company, String>();
        vMap.put(Company._21ST_CENTURY_INSURANCE,"21st Century Insurance");
        vMap.put(Company._AAA_AUTO_CLUB,"AAA Insurance Co. ");
        vMap.put(Company._AIU_INSURANCE,"AIU Insurance");
        vMap.put(Company._ALLIED,"Allied");
        vMap.put(Company._ALLSTATE,"Allstate Insurance");
        vMap.put(Company._AMERICAN_ALLIANCE_INSURANCE,"American Alliance Insurance");
        vMap.put(Company._AMERICAN_AUTOMOBILE_INSURANCE,"American Automobile Insurance");
        vMap.put(Company._AMERICAN_CASUALTY,"American Casualty");
        vMap.put(Company._AMERICAN_DEPOSIT_INSURANCE,"American Deposit Insurance");
        vMap.put(Company._AMERICAN_DIRECT_BUSINESS_INSURANCE,"American Direct Business Insurance");
        vMap.put(Company._AMERICAN_EMPIRE_INSURANCE,"American Empire Insurance");
        vMap.put(Company._AMERICAN_FAMILY,"American Family Insurance");
        vMap.put(Company._AMERICAN_FINANCIAL,"American Financial");
        vMap.put(Company._AMERICAN_HOME_ASSURANCE,"American Home Assurance");
        vMap.put(Company._AMERICAN_INSURANCE,"American Insurance");
        vMap.put(Company._AMERICAN_INTERNATIONAL_INS,"American International Ins");
        vMap.put(Company._AMERICAN_INTERNATIONAL_PACIFIC,"American International Pacific");
        vMap.put(Company._AMERICAN_INTERNATIONAL_SOUTH,"American International South");
        vMap.put(Company._AMERICAN_MANUFACTURERS,"American Manufacturers");
        vMap.put(Company._AMERICAN_MAYFLOWER_INSURANCE,"American Mayflower Insurance");
        vMap.put(Company._AMERICAN_MOTORISTS_INSURANCE,"American Motorists Insurance");
        vMap.put(Company._AMERICAN_NATIONAL_INSURANCE,"American National Insurance");
        vMap.put(Company._AMERICAN_PREMIER_INSURANCE,"American Premier Insurance");
        vMap.put(Company._AMERICAN_PROTECTION_INSURANCE,"American Protection Insurance");
        vMap.put(Company._AMERICAN_SERVICE_INSURANCE,"American Service Insurance");
        vMap.put(Company._AMERICAN_SKYLINE_INSURANCE_COMPANY,"American Skyline Insurance Company");
        vMap.put(Company._AMERICAN_SPIRIT_INSURANCE,"American Spirit Insurance");
        vMap.put(Company._AMERICAN_STANDARD_INSURANCE_OH,"American Standard Insurance - OH");
        vMap.put(Company._AMERICAN_STANDARD_INSURANCE_WI,"American Standard Insurance - WI");
        vMap.put(Company._AMICA,"Amica Insurance");
        vMap.put(Company._ARBELLA,"Arbella");
        vMap.put(Company._ASSOCIATED_INDEMNITY,"Associated Indemnity");
        vMap.put(Company._ATLANTA_CASUALTY,"Atlanta Casualty");
        vMap.put(Company._ATLANTIC_INDEMNITY,"Atlantic Indemnity");
        vMap.put(Company._AUTO_CLUB_INSURANCE_COMPANY,"Auto Club Insurance Company");
        vMap.put(Company._AUTO_OWNERS,"Company Not Listed");
        vMap.put(Company._BLUE_CROSS_AND_BLUE_SHIELD,"Blue Cross and Blue Shield");
        vMap.put(Company._CAL_FARM_INSURANCE,"Cal Farm Insurance");
        vMap.put(Company._CALIFORNIA_STATE_AUTOMOBILE_ASSOCIATION,"California State Automobile Association");
        vMap.put(Company._CHUBB,"Chubb");
        vMap.put(Company._CITIZENS,"Citizens");
        vMap.put(Company._CLARENDON_AMERICAN_INSURANCE,"Clarendon American Insurance");
        vMap.put(Company._CLARENDON_NATIONAL_INSURANCE,"Clarendon National Insurance");
        vMap.put(Company._CNA,"CNA");
        vMap.put(Company._COLONIAL_INSURANCE,"Colonial Insurance");
        vMap.put(Company._CONTINENTAL_CASUALTY,"Continental Casualty");
        vMap.put(Company._CONTINENTAL_DIVIDE_INSURANCE,"Continental Divide Insurance");
        vMap.put(Company._CONTINENTAL_INSURANCE,"Continental Insurance");
        vMap.put(Company._COTTON_STATES_INSURANCE,"Cotton States Insurance");
        vMap.put(Company._COUNTRY_INSURANCE_FINANCIAL_SERVICES,"Country Insurance and Financial Services");
        vMap.put(Company._DAIRYLAND_COUNTY_MUTUAL_CO_OF_TX,"Dairyland County Mutual Co of TX");
        vMap.put(Company._DAIRYLAND_INSURANCE,"Dairyland Insurance");
        vMap.put(Company._EASTWOOD_INSURANCE,"Company Not Listed");
        vMap.put(Company._ELECTRIC_INSURANCE,"Electric Insurance");
        vMap.put(Company._ERIE,"Erie Insurance Company");
        vMap.put(Company._ESURANCE,"Esurance");
        vMap.put(Company._FARM_BUREAU,"Farm Bureau/Farm Family/Rural");
        vMap.put(Company._FARMERS,"Farmers Insurance");
        vMap.put(Company._FIRE_AND_CASUALTY_INSURANCE_CO_OF_CT,"Fire and Casualty Insurance Co of CT");
        vMap.put(Company._FIREMANS_FUND,"Fireman's Fund");
        vMap.put(Company._GEICO,"Geico General Insurance");
        vMap.put(Company._GMAC_INSURANCE,"GMAC Insurance");
        vMap.put(Company._GOLDEN_RULE_INSURANCE,"Golden Rule Insurance");
        vMap.put(Company._GOVERNMENT_EMPLOYEES_INSURANCE,"Government Employees Insurance");
        vMap.put(Company._GRANGE,"Company Not Listed");
        vMap.put(Company._GUARANTY_NATIONAL_INSURANCE,"Guaranty National Insurance");
        vMap.put(Company._HANOVER_LLOYDS_INSURANCE_COMPANY,"Hanover Lloyd's Insurance Company");
        vMap.put(Company._HEALTH_PLUS_OF_AMERICA,"Health Plus of America");
        vMap.put(Company._IFA_AUTO_INSURANCE,"IFA Auto Insurance");
        vMap.put(Company._IGF_INSURANCE,"IGF Insurance");
        vMap.put(Company._INFINITY_INSURANCE,"Infinity Insurance");
        vMap.put(Company._INFINITY_NATIONAL_INSURANCE,"Infinity National Insurance");
        vMap.put(Company._INFINITY_SELECT_INSURANCE,"Infinity Select Insurance");
        vMap.put(Company._INTEGON,"Integon");
        vMap.put(Company._KAISER_PERMANENTE,"Kaiser Permanente");
        vMap.put(Company._KEMPER_LLOYDS_INSURANCE,"Kemper Lloyds Insurance");
        vMap.put(Company._LANDMARK_AMERICAN_INSURANCE,"Landmark American Insurance");
        vMap.put(Company._LEADER_NATIONAL_INSURANCE,"Leader National Insurance");
        vMap.put(Company._LEADER_PREFERRED_INSURANCE,"Leader Preferred Insurance");
        vMap.put(Company._LEADER_SPECIALTY_INSURANCE,"Leader Specialty Insurance");
        vMap.put(Company._LIBERTY_INSURANCE_CORP,"Liberty Insurance Corp");
        vMap.put(Company._LIBERTY_MUTUAL,"Liberty Mutual Insurance");
        vMap.put(Company._LIBERTY_NORTHWEST_INSURANCE,"Liberty Northwest Insurance");
        vMap.put(Company._LUMBERMENS_MUTUAL,"Lumbermens Mutual");
        vMap.put(Company._MASS_MUTUAL,"Mass Mutual");
        vMap.put(Company._MERCURY,"Mercury");
        vMap.put(Company._METLIFE,"MetLife Auto and Home");
        vMap.put(Company._METROPOLITAN_INSURANCE_CO,"Metropolitan Insurance Co.");
        vMap.put(Company._MID_CENTURY_INSURANCE,"Mid Century Insurance");
        vMap.put(Company._MID_CONTINENT_CASUALTY,"Mid-Continent Casualty");
        vMap.put(Company._MIDDLESEX_INSURANCE,"Middlesex Insurance");
        vMap.put(Company._MIDWEST_NATIONAL_LIFE,"Company Not Listed");
        vMap.put(Company._MSI_INSURANCE,"Company Not Listed");
        vMap.put(Company._MUTUAL_OF_NEW_YORK,"Mutual of New York");
        vMap.put(Company._MUTUAL_OF_OMAHA,"Mutual of Omaha");
        vMap.put(Company._NATIONAL_BEN_FRANKLIN_INSURANCE,"National Ben Franklin Insurance");
        vMap.put(Company._NATIONAL_CASUALTY,"National Casualty");
        vMap.put(Company._NATIONAL_CONTINENTAL_INSURANCE,"National Continental Insurance");
        vMap.put(Company._NATIONAL_FIRE_INSURANCE_COMPANY_OF_HARTFORD,"National Fire Insurance Company of Hartford");
        vMap.put(Company._NATIONAL_HEALTH_INSURANCE,"National Health Insurance");
        vMap.put(Company._NATIONAL_INDEMNITY,"National Indemnity");
        vMap.put(Company._NATIONAL_UNION_FIRE_INSURANCE_OF_LA,"National Union Fire Insurance of LA");
        vMap.put(Company._NATIONAL_UNION_FIRE_INSURANCE_OF_PA,"National Union Fire Insurance of PA");
        vMap.put(Company._NATIONWIDE,"Nationwide Insurance Company");
        vMap.put(Company._NEW_YORK_LIFE,"New York Life Insurance");
        vMap.put(Company._NORTHWESTERN_MUTUAL_LIFE,"Northwestern Mutual Life");
        vMap.put(Company._NORTHWESTERN_PACIFIC_INDEMNITY,"Northwestern Pacific Indemnity");
        vMap.put(Company._OMNI_INDEMNITY,"Omni Indemnity");
        vMap.put(Company._OMNI_INSURANCE,"Omni Insurance");
        vMap.put(Company._ORION_INSURANCE,"Orion Insurance");
        vMap.put(Company._PACIFIC_INDEMNITY,"Pacific Indemnity");
        vMap.put(Company._PACIFIC_INSURANCE,"Pacific Insurance");
        vMap.put(Company._PAFCO_GENERAL_INSURANCE,"Pafco General Insurance");
        vMap.put(Company._PATRIOT_GENERAL_INSURANCE,"Patriot General Insurance");
        vMap.put(Company._PEAK_PROPERTY_AND_CASUALTY_INSURANCE,"Peak Property and Casualty Insurance");
        vMap.put(Company._PEMCO_INSURANCE,"PEMCO Insurance");
        vMap.put(Company._PROGRESSIVE,"Progressive");
        vMap.put(Company._PROGRESSIVE_AUTO_PRO,"Progressive Auto Pro");
        vMap.put(Company._PRUDENTIAL,"Prudential Insurance Co.");
        vMap.put(Company._RELIANCE_INSURANCE,"Reliance Insurance");
        vMap.put(Company._RELIANCE_NATIONAL_INDEMNITY,"Reliance National Indemnity");
        vMap.put(Company._RELIANCE_NATIONAL_INSURANCE,"Reliance National Insurance");
        vMap.put(Company._REPUBLIC_INDEMNITY,"Republic Indemnity");
        vMap.put(Company._RESPONSE_INSURANCE,"Response Insurance");
        vMap.put(Company._SAFECO,"SAFECO");
        vMap.put(Company._SAFEWAY_INSURANCE,"Safeway Insurance");
        vMap.put(Company._SAFEWAY_INSURANCE_CO_OF_AL,"Safeway Insurance Co of AL");
        vMap.put(Company._SAFEWAY_INSURANCE_CO_OF_GA,"Safeway Insurance Co of GA");
        vMap.put(Company._SAFEWAY_INSURANCE_CO_OF_LA,"Safeway Insurance Co of LA");
        vMap.put(Company._SECURITY_INSURANCE_CO_OF_HARTFORD,"Security Insurance Co of Hartford");
        vMap.put(Company._SECURITY_NATIONAL_INSURANCE_CO_OF_FL,"Security National Insurance Co of FL");
        vMap.put(Company._SENTINEL_INSURANCE,"Sentinel Insurance");
        vMap.put(Company._SENTRY_INSURANCE_A_MUTUAL_COMPANY,"Sentry Insurance a Mutual Company");
        vMap.put(Company._SENTRY_INSURANCE_GROUP,"Sentry Insurance Group");
        vMap.put(Company._SHELTER_INSURANCE_CO,"Shelter Insurance Co.");
        vMap.put(Company._ST_PAUL,"St. Paul");
        vMap.put(Company._ST_PAUL_FIRE_AND_MARINE,"St. Paul Fire and Marine");
        vMap.put(Company._ST_PAUL_INSURANCE,"St. Paul Insurance");
        vMap.put(Company._STANDARD_FIRE_INSURANCE_COMPANY,"Standard Fire Insurance Company");
        vMap.put(Company._STATE_AND_COUNTY_MUTUAL_FIRE_INSURANCE,"State and County Mutual Fire Insurance");
        vMap.put(Company._STATE_FARM,"State Farm Insurance Co.");
        vMap.put(Company._STATE_FARM_MUTUAL_AUTO,"State Farm Mutual Auto");
        vMap.put(Company._STATE_NATIONAL_INSURANCE,"State National Insurance");
        vMap.put(Company._SUPERIOR_AMERICAN_INSURANCE,"Superior American Insurance");
        vMap.put(Company._SUPERIOR_GUARANTY_INSURANCE,"Superior Guaranty Insurance");
        vMap.put(Company._SUPERIOR_INSURANCE,"Superior Insurance");
        vMap.put(Company._THE_AHBE_GROUP,"The Ahbe Group");
        vMap.put(Company._THE_GENERAL,"The General");
        vMap.put(Company._THE_HARTFORD,"The Hartford");
        vMap.put(Company._TICO_INSURANCE,"TICO Insurance");
        vMap.put(Company._TIG_COUNTRYWIDE_INSURANCE,"TIG Countrywide Insurance");
        vMap.put(Company._TRAVELERS,"Travelers Insurance Company");
        vMap.put(Company._TRAVELERS_INDEMNITY,"Travelers Indemnity");
        vMap.put(Company._TRI_STATE_CONSUMER_INSURANCE,"Tri-State Consumer Insurance");
        vMap.put(Company._TWIN_CITY_FIRE_INSURANCE,"Twin City Fire Insurance");
        vMap.put(Company._UNICARE,"UniCare");
        vMap.put(Company._UNITED_PACIFIC_INSURANCE,"United Pacific Insurance");
        vMap.put(Company._UNITED_SECURITY,"United Security");
        vMap.put(Company._UNITED_SERVICES_AUTOMOBILE_ASSOCIATION,"United Services Automobile Association");
        vMap.put(Company._UNITRIN_DIRECT,"Unitrin Direct");
        vMap.put(Company._USAA,"USAA");
        vMap.put(Company._USF_AND_G,"USF and G");
        vMap.put(Company._VIKING_COUNTY_MUTUAL_INSURANCE,"Viking County Mutual Insurance");
        vMap.put(Company._VIKING_INSURANCE_CO_OF_WI,"Viking Insurance Co of WI");
        vMap.put(Company._WINDSOR_INSURANCE,"Windsor Insurance");
        vMap.put(Company._WOODLANDS_FINANCIAL_GROUP,"Woodlands Financial Group");
        vMap.put(Company._COMPANY_NOT_LISTED, "Company Not Listed");

        mMap = Collections.unmodifiableMap(vMap);
    }

    public static String valueOf(Company iKey)
    {
        if (iKey == null)
            return DEFAULT;
        return mMap.get(iKey);
    }
}
